package app.sillage.ui.application

import app.sillage.core.application.preferences.ClientPreferenceValues
import app.sillage.core.domain.ask.AskSourceRef
import app.sillage.features.records.MemoListFilter
import app.sillage.ui.records.SillageRecordDetailActionStrings
import app.sillage.ui.records.SillageRecordDetailStrings
import app.sillage.ui.records.SillageRecordFilterStrings
import app.sillage.ui.records.SillageRecordRowStrings
import app.sillage.ui.records.SillageRecordSearchStrings

internal class SillageNativeAskStrings(
    val navigationLabel: String,
    val title: String,
    val savingAnswerDescription: String,
    val conversationsDescription: String,
    val contextDescription: String,
    val newConversationDescription: String,
    val recentSevenDays: String,
    val recentThirtyDays: String,
    val allTime: String,
    val recordsSource: String,
    val summariesSource: String,
    val conversationsTitle: String,
    val refresh: String,
    val noConversations: String,
    val untitledConversation: String,
    val currentConversation: (title: String) -> String,
    val contextTitle: String,
    val timeRange: String,
    val recentSevenDaysShort: String,
    val recentThirtyDaysShort: String,
    val allTimeShort: String,
    val sourceTitle: String,
    val questionLabel: String,
    val sendDescription: String,
    val stopDescription: String,
    val contextSummary: (scope: String, source: String) -> String,
    val characterCount: (count: Int) -> String,
    val loadFailed: String,
    val retry: String,
    val promptTitle: String,
    val promptExample: String,
    val regenerating: String,
    val thinking: String,
    val messageDescription: (isAssistant: Boolean, content: String) -> String,
    val sourceCount: (count: Int) -> String,
    val sourceLabel: (source: AskSourceRef) -> String,
    val showSourcesDescription: String,
    val hideSourcesDescription: String,
    val previousVariantDescription: String,
    val nextVariantDescription: String,
    val variantCounter: (position: Int, total: Int) -> String,
    val variantPositionDescription: (position: Int, total: Int) -> String,
    val regenerateDescription: String,
    val generatingDescription: String,
    val saveAsRecordDescription: String,
    val savingDescription: String,
    val answerCompleteDescription: String,
    val authenticationRequired: String,
    val questionRequired: String,
    val sendFailed: String,
    val variantFailed: String,
    val sourceUnavailable: String,
    val saveFailed: String,
)

internal data class SillageNativeStrings(
    val appName: String,
    val records: String,
    val settings: String,
    val localMode: String,
    val newRecord: String,
    val saveRecord: String,
    val savingRecord: String,
    val back: String,
    val close: String,
    val recordDetails: String,
    val editRecord: String,
    val editorTitleNew: String,
    val editorTitleEdit: String,
    val entryDate: String,
    val entryDatePlaceholder: String,
    val content: String,
    val contentPlaceholder: String,
    val emptyRecordContent: String,
    val recordContentTooLarge: String,
    val invalidEntryDate: String,
    val noSelection: String,
    val noSearchResults: String,
    val emptyByFilter: Map<MemoListFilter, String>,
    val restore: String,
    val purge: String,
    val purgeTitle: String,
    val purgeSupporting: String,
    val confirm: String,
    val cancel: String,
    val discardTitle: String,
    val discardSupporting: String,
    val discard: String,
    val appearance: String,
    val darkTheme: String,
    val darkThemeSupporting: String,
    val language: String,
    val languageSupporting: String,
    val simplifiedChinese: String,
    val english: String,
    val data: String,
    val dataLocation: String,
    val openDataLocation: String,
    val openDataLocationSupporting: String,
    val exportBackup: String,
    val exportBackupSupporting: String,
    val restoreBackup: String,
    val restoreBackupSupporting: String,
    val restoreBackupTitle: String,
    val restoreBackupWarning: String,
    val platform: String,
    val version: String,
    val about: String,
    val openSourceLicenses: String,
    val openSourceLicensesSupporting: String,
    val service: String,
    val serverAddress: String,
    val serverAddressPlaceholder: String,
    val checkServer: String,
    val checkingServer: String,
    val serverConnection: String,
    val serverConnectionAvailable: String,
    val serverConnectionFailed: String,
    val serverInitialization: String,
    val serverInitialized: String,
    val serverNeedsInitialization: String,
    val serverVersion: String,
    val apiVersion: String,
    val unknownValue: String,
    val accountSection: String,
    val changePassword: String,
    val changePasswordSupporting: String,
    val currentPassword: String,
    val newPassword: String,
    val confirmPassword: String,
    val savePassword: String,
    val initializeAccountSupporting: String,
    val signInSupporting: String,
    val username: String,
    val displayName: String,
    val password: String,
    val showPassword: String,
    val hidePassword: String,
    val initializeAccount: String,
    val initializingAccount: String,
    val signIn: String,
    val signingIn: String,
    val authenticatedAccount: String,
    val sessionPersistence: String,
    val sessionMemoryOnly: String,
    val sessionDeviceProtected: String,
    val syncMemos: String,
    val syncMemosSupporting: String,
    val signOut: String,
    val signingOut: String,
    val syncConflictTitle: String,
    val syncConflictSupporting: String,
    val syncConflictLocalLabel: String,
    val syncConflictServerLabel: String,
    val syncConflictEmptyLocal: String,
    val syncConflictEmptyServer: String,
    val syncConflictKeepLocal: String,
    val syncConflictTakeServer: String,
    val syncConflictDismiss: String,
    val authRequiredFields: String,
    val passwordChangeRequiredFields: String,
    val passwordChangeConfirmationMismatch: String,
    val passwordChangeUnchanged: String,
    val passwordChangeInvalidCurrent: String,
    val authInvalidRequest: String,
    val authInvalidCredentials: String,
    val authAlreadyInitialized: String,
    val authRateLimited: String,
    val authSessionExpired: String,
    val authServerRejected: String,
    val authInvalidResponse: String,
    val authSecureStorageUnavailable: String,
    val authConnectionFailed: String,
    val mode: String,
    val offlineModeValue: String,
    val saved: String,
    val deleted: String,
    val restored: String,
    val purged: String,
    val backupExported: String,
    val backupRestored: String,
    val accountInitialized: String,
    val signedIn: String,
    val passwordChanged: String,
    val signedOut: String,
    val signedOutLocally: String,
    val memoSyncCompleted: String,
    val memoSyncNoChanges: String,
    val memoSyncNeedsReview: String,
    val memoSyncRejected: String,
    val memoSyncFailed: String,
    val memoSyncServerMismatch: String,
    val memoSyncSessionExpired: String,
    val memoSyncConflictResolved: String,
    val askGenerationStopped: String,
    val askAnswerSaved: String,
    val dataTransferFailed: String,
    val storageUnavailable: String,
    val recordFilter: SillageRecordFilterStrings,
    val recordSearch: SillageRecordSearchStrings,
    val recordRow: SillageRecordRowStrings,
    val recordDetail: SillageRecordDetailStrings,
    val recordActions: SillageRecordDetailActionStrings,
    val ask: SillageNativeAskStrings,
)

internal fun sillageNativeStrings(language: String): SillageNativeStrings {
    return if (language == ClientPreferenceValues.LANGUAGE_EN) englishStrings else chineseStrings
}

private val englishStrings = SillageNativeStrings(
    appName = "Sillage",
    records = "Records",
    settings = "Settings",
    localMode = "Local",
    newRecord = "New record",
    saveRecord = "Save record",
    savingRecord = "Saving record",
    back = "Back",
    close = "Close",
    recordDetails = "Record",
    editRecord = "Edit record",
    editorTitleNew = "New record",
    editorTitleEdit = "Edit record",
    entryDate = "Entry date",
    entryDatePlaceholder = "YYYY-MM-DD",
    content = "Content",
    contentPlaceholder = "Write a record...",
    emptyRecordContent = "Write something before saving.",
    recordContentTooLarge = "Keep record content within 1 MiB.",
    invalidEntryDate = "Enter a valid date in YYYY-MM-DD format.",
    noSelection = "Select a record",
    noSearchResults = "No matching records",
    emptyByFilter = mapOf(
        MemoListFilter.Unarchived to "No records yet",
        MemoListFilter.Archived to "No archived records",
        MemoListFilter.Favorited to "No favorite records",
        MemoListFilter.Deleted to "Recently Deleted is empty",
    ),
    restore = "Restore",
    purge = "Delete permanently",
    purgeTitle = "Delete permanently?",
    purgeSupporting = "This record cannot be restored after permanent deletion.",
    confirm = "Delete",
    cancel = "Cancel",
    discardTitle = "Discard changes?",
    discardSupporting = "Your unsaved changes will be lost.",
    discard = "Discard",
    appearance = "Appearance",
    darkTheme = "Dark theme",
    darkThemeSupporting = "Use the dark Sillage color scheme",
    language = "Language",
    languageSupporting = "Choose the interface language",
    simplifiedChinese = "Simplified Chinese",
    english = "English",
    data = "Data",
    dataLocation = "Local data",
    openDataLocation = "Open data folder",
    openDataLocationSupporting = "Show the device-local snapshot",
    exportBackup = "Export backup",
    exportBackupSupporting = "Save records and appearance as JSON",
    restoreBackup = "Restore backup",
    restoreBackupSupporting = "Replace local data from a Sillage JSON backup",
    restoreBackupTitle = "Restore this backup?",
    restoreBackupWarning = "Current records and appearance will be replaced. This cannot be undone.",
    platform = "Platform",
    version = "Version",
    about = "About",
    openSourceLicenses = "Open-source licenses",
    openSourceLicensesSupporting = "Review licenses and notices included with this app",
    service = "Service",
    serverAddress = "Sillage server",
    serverAddressPlaceholder = "https://sillage.example",
    checkServer = "Check server",
    checkingServer = "Checking server",
    serverConnection = "Connection",
    serverConnectionAvailable = "Available",
    serverConnectionFailed = "Could not reach a compatible Sillage server. Check the address and try again.",
    serverInitialization = "Instance",
    serverInitialized = "Initialized",
    serverNeedsInitialization = "Not initialized",
    serverVersion = "Server version",
    apiVersion = "API version",
    unknownValue = "Unknown",
    accountSection = "Account",
    changePassword = "Change password",
    changePasswordSupporting = "Changing it signs out every other session.",
    currentPassword = "Current password",
    newPassword = "New password",
    confirmPassword = "Confirm new password",
    savePassword = "Save password",
        initializeAccountSupporting =
            "Create the only account. Local changes are then pushed to this server before its current records are pulled.",
        signInSupporting =
            "Signing in pushes local changes to this server before pulling its current records.",
    username = "Username",
    displayName = "Display name",
    password = "Password",
    showPassword = "Show password",
    hidePassword = "Hide password",
    initializeAccount = "Create account",
    initializingAccount = "Creating account",
    signIn = "Sign in",
    signingIn = "Signing in",
    authenticatedAccount = "Authenticated account",
    sessionPersistence = "Session storage",
    sessionMemoryOnly = "Memory only; sign in again after closing Sillage",
    sessionDeviceProtected = "Protected by this device; restored after relaunch",
    syncMemos = "Sync records",
        syncMemosSupporting = "Push device changes, then pull current records from this server",
    signOut = "Sign out",
    signingOut = "Signing out",
    syncConflictTitle = "Sync conflict",
    syncConflictSupporting = "This record changed on both the device and server. Choose which version to keep.",
    syncConflictLocalLabel = "Device version",
    syncConflictServerLabel = "Server version",
    syncConflictEmptyLocal = "No local content",
    syncConflictEmptyServer = "No server content",
    syncConflictKeepLocal = "Keep device version",
    syncConflictTakeServer = "Use server version",
    syncConflictDismiss = "Review later",
    authRequiredFields = "Enter a username and password.",
    passwordChangeRequiredFields = "Enter the current and new passwords.",
    passwordChangeConfirmationMismatch = "The new passwords do not match.",
    passwordChangeUnchanged = "Choose a new password different from the current password.",
    passwordChangeInvalidCurrent = "The current password is incorrect.",
    authInvalidRequest = "Check the account fields and password requirements.",
    authInvalidCredentials = "The username or password is incorrect.",
    authAlreadyInitialized = "This instance was initialized elsewhere. Sign in instead.",
    authRateLimited = "Too many attempts. Wait a moment and try again.",
    authSessionExpired = "The session expired. Sign in again.",
    authServerRejected = "The server could not complete authentication.",
    authInvalidResponse = "The server returned an incompatible authentication response.",
    authSecureStorageUnavailable =
        "Secure session storage is unavailable. Unlock the device and try again.",
    authConnectionFailed = "Authentication could not reach the Sillage server.",
    mode = "Mode",
        offlineModeValue = "Local-first · automatic + manual sync",
    saved = "Record saved",
    deleted = "Record moved to Recently Deleted",
    restored = "Record restored",
    purged = "Record permanently deleted",
    backupExported = "Backup exported",
    backupRestored = "Backup restored",
    accountInitialized = "Account created",
    signedIn = "Signed in",
    passwordChanged = "Password changed; other sessions were signed out",
    signedOut = "Signed out",
    signedOutLocally = "Signed out on this device; the server session will expire automatically",
    memoSyncCompleted = "Record sync complete",
        memoSyncNoChanges = "Records are already up to date",
    memoSyncNeedsReview = "Some record changes need conflict review",
    memoSyncRejected = "The server rejected some changes; they remain pending",
        memoSyncFailed = "Record sync failed; local data was kept",
    memoSyncServerMismatch = "Pending changes remain bound to the previous server and were not sent",
    memoSyncSessionExpired = "The session expired. Sign in again before syncing.",
    memoSyncConflictResolved = "Sync conflict resolved",
    askGenerationStopped = "Answer generation stopped",
    askAnswerSaved = "Answer saved as a record",
    dataTransferFailed = "The backup could not be read or written. Existing data was not changed.",
    storageUnavailable = "Local data could not be read. Existing data was not changed.",
    recordFilter = SillageRecordFilterStrings(
        unarchived = "Records",
        archived = "Archived",
        favorited = "Favorites",
        deleted = "Deleted",
    ),
    recordSearch = SillageRecordSearchStrings(
        label = "Search records",
        clearContentDescription = "Clear search",
        searchContentDescription = "Search",
    ),
    recordRow = SillageRecordRowStrings(
        blankRecord = "Blank record",
        entryDateLabel = "Entry date",
        moreActionsLabel = "More record actions",
        savingDescription = "Saving record",
        favoritedStatus = "Favorite",
        archivedStatus = "Archived",
    ),
    recordDetail = SillageRecordDetailStrings(
        entryDateLabel = "Entry date",
        blankRecord = "Blank record",
        favoritedStatus = "Favorite",
        archivedStatus = "Archived",
    ),
    recordActions = SillageRecordDetailActionStrings(
        editContentDescription = "Edit record",
        moreContentDescription = "More record actions",
        favoriteAction = "Add to favorites",
        unfavoriteAction = "Remove from favorites",
        archiveAction = "Archive",
        unarchiveAction = "Unarchive",
        deleteAction = "Move to Recently Deleted",
        deleteTitle = "Delete record?",
        deleteSupporting = "You can restore this record from Recently Deleted.",
        confirmDeleteAction = "Delete",
        cancelAction = "Cancel",
    ),
    ask = SillageNativeAskStrings(
        navigationLabel = "Ask",
        title = "Ask",
        savingAnswerDescription = "Saving answer as a record",
        conversationsDescription = "Conversations",
        contextDescription = "Answer context",
        newConversationDescription = "New conversation",
        recentSevenDays = "Past 7 days",
        recentThirtyDays = "Past 30 days",
        allTime = "All time",
        recordsSource = "Records",
        summariesSource = "Summaries",
        conversationsTitle = "Conversations",
        refresh = "Refresh",
        noConversations = "No conversations yet",
        untitledConversation = "Untitled conversation",
        currentConversation = { title -> "Current: $title" },
        contextTitle = "Answer context",
        timeRange = "Time range",
        recentSevenDaysShort = "7 days",
        recentThirtyDaysShort = "30 days",
        allTimeShort = "All time",
        sourceTitle = "Source",
        questionLabel = "Question",
        sendDescription = "Send question",
        stopDescription = "Stop generation",
        contextSummary = { scope, source -> "$scope · $source" },
        characterCount = { count ->
            if (count == 1) "1 character" else "$count characters"
        },
        loadFailed = "Conversations could not be loaded.",
        retry = "Retry",
        promptTitle = "Ask your records",
        promptExample = "What changed in my work over the last month?",
        regenerating = "Regenerating answer...",
        thinking = "Thinking...",
        messageDescription = { isAssistant, content ->
            "${if (isAssistant) "Sillage" else "You"}: $content"
        },
        sourceCount = { count -> if (count == 1) "1 source" else "$count sources" },
        sourceLabel = { source -> "${source.entryDate} · ${source.excerpt}" },
        showSourcesDescription = "Show sources",
        hideSourcesDescription = "Hide sources",
        previousVariantDescription = "Previous answer variant",
        nextVariantDescription = "Next answer variant",
        variantCounter = { position, total -> "$position / $total" },
        variantPositionDescription = { position, total ->
            "Answer variant $position of $total"
        },
        regenerateDescription = "Regenerate answer",
        generatingDescription = "Generating answer",
        saveAsRecordDescription = "Save answer as record",
        savingDescription = "Saving answer",
        answerCompleteDescription = "Answer complete",
        authenticationRequired = "Sign in to a checked Sillage server to use Ask.",
        questionRequired = "Enter a question before sending.",
        sendFailed = "The answer could not be generated. Your question was kept.",
        variantFailed = "The answer variant could not be changed.",
        sourceUnavailable = "That source record is not available on this device.",
        saveFailed = "The answer could not be saved as a record.",
    ),
)

private val chineseStrings = SillageNativeStrings(
    appName = "Sillage",
    records = "记录",
    settings = "设置",
    localMode = "本地",
    newRecord = "新建记录",
    saveRecord = "保存记录",
    savingRecord = "正在保存记录",
    back = "返回",
    close = "关闭",
    recordDetails = "记录",
    editRecord = "编辑记录",
    editorTitleNew = "新建记录",
    editorTitleEdit = "编辑记录",
    entryDate = "记录日期",
    entryDatePlaceholder = "YYYY-MM-DD",
    content = "内容",
    contentPlaceholder = "写下这条记录……",
    emptyRecordContent = "请输入记录内容。",
    recordContentTooLarge = "记录内容不能超过 1 MiB。",
    invalidEntryDate = "请输入 YYYY-MM-DD 格式的有效日期。",
    noSelection = "选择一条记录",
    noSearchResults = "没有匹配的记录",
    emptyByFilter = mapOf(
        MemoListFilter.Unarchived to "还没有记录",
        MemoListFilter.Archived to "没有已归档记录",
        MemoListFilter.Favorited to "没有收藏记录",
        MemoListFilter.Deleted to "最近删除为空",
    ),
    restore = "恢复",
    purge = "永久删除",
    purgeTitle = "永久删除？",
    purgeSupporting = "永久删除后无法恢复这条记录。",
    confirm = "删除",
    cancel = "取消",
    discardTitle = "放弃更改？",
    discardSupporting = "尚未保存的更改将会丢失。",
    discard = "放弃",
    appearance = "外观",
    darkTheme = "深色主题",
    darkThemeSupporting = "使用 Sillage 深色配色",
    language = "语言",
    languageSupporting = "选择界面语言",
    simplifiedChinese = "简体中文",
    english = "English",
    data = "数据",
    dataLocation = "本地数据",
    openDataLocation = "打开数据文件夹",
    openDataLocationSupporting = "查看保存在设备上的快照",
    exportBackup = "导出备份",
    exportBackupSupporting = "将记录和外观设置保存为 JSON",
    restoreBackup = "恢复备份",
    restoreBackupSupporting = "用 Sillage JSON 备份替换本地数据",
    restoreBackupTitle = "恢复这个备份？",
    restoreBackupWarning = "当前记录和外观设置将被替换，且无法撤销。",
    platform = "平台",
    version = "版本",
    about = "关于",
    openSourceLicenses = "开源软件许可",
    openSourceLicensesSupporting = "查看本应用所含开源软件的许可与声明",
    service = "服务",
    serverAddress = "Sillage 服务器",
    serverAddressPlaceholder = "https://sillage.example",
    checkServer = "检查服务器",
    checkingServer = "正在检查服务器",
    serverConnection = "连接状态",
    serverConnectionAvailable = "可用",
    serverConnectionFailed = "无法连接兼容的 Sillage 服务器，请检查地址后重试。",
    serverInitialization = "实例状态",
    serverInitialized = "已初始化",
    serverNeedsInitialization = "未初始化",
    serverVersion = "服务器版本",
    apiVersion = "API 版本",
    unknownValue = "未知",
    accountSection = "账号",
    changePassword = "修改密码",
    changePasswordSupporting = "修改后，其他设备上的会话将退出登录。",
    currentPassword = "当前密码",
    newPassword = "新密码",
    confirmPassword = "确认新密码",
    savePassword = "保存密码",
        initializeAccountSupporting =
            "创建此实例的唯一账号。随后会先将本机更改推送到这台服务器，再拉取服务器上的当前记录。",
        signInSupporting =
            "登录会先将本机更改推送到这台服务器，再拉取服务器上的当前记录。",
    username = "账号",
    displayName = "显示名",
    password = "密码",
    showPassword = "显示密码",
    hidePassword = "隐藏密码",
    initializeAccount = "创建账号",
    initializingAccount = "正在创建账号",
    signIn = "登录",
    signingIn = "正在登录",
    authenticatedAccount = "已认证账号",
    sessionPersistence = "会话存储",
    sessionMemoryOnly = "仅保存在内存中；关闭 Sillage 后需重新登录",
    sessionDeviceProtected = "受本设备安全存储保护；重新打开后自动恢复",
    syncMemos = "同步记录",
        syncMemosSupporting = "先推送本机更改，再拉取服务器上的最新记录",
    signOut = "退出登录",
    signingOut = "正在退出登录",
    syncConflictTitle = "同步冲突",
    syncConflictSupporting = "这条记录在本机和服务器上都发生了更改，请选择保留的版本。",
    syncConflictLocalLabel = "本机版本",
    syncConflictServerLabel = "服务器版本",
    syncConflictEmptyLocal = "本机无内容",
    syncConflictEmptyServer = "服务器无内容",
    syncConflictKeepLocal = "保留本机版本",
    syncConflictTakeServer = "采用服务器版本",
    syncConflictDismiss = "稍后处理",
    authRequiredFields = "请填写账号和密码。",
    passwordChangeRequiredFields = "请填写当前密码和新密码。",
    passwordChangeConfirmationMismatch = "两次输入的新密码不一致。",
    passwordChangeUnchanged = "新密码不能与当前密码相同。",
    passwordChangeInvalidCurrent = "当前密码不正确。",
    authInvalidRequest = "请检查账号信息和密码要求。",
    authInvalidCredentials = "账号或密码不正确。",
    authAlreadyInitialized = "这个实例已在其他位置完成初始化，请直接登录。",
    authRateLimited = "尝试次数过多，请稍后重试。",
    authSessionExpired = "登录会话已过期，请重新登录。",
    authServerRejected = "服务器未能完成认证。",
    authInvalidResponse = "服务器返回了不兼容的认证响应。",
    authSecureStorageUnavailable = "无法使用安全会话存储，请解锁设备后重试。",
    authConnectionFailed = "认证请求无法连接 Sillage 服务器。",
    mode = "模式",
        offlineModeValue = "本地优先 · 自动 + 手动同步",
    saved = "记录已保存",
    deleted = "记录已移至最近删除",
    restored = "记录已恢复",
    purged = "记录已永久删除",
    backupExported = "备份已导出",
    backupRestored = "备份已恢复",
    accountInitialized = "账号已创建",
    signedIn = "已登录",
    passwordChanged = "密码已修改，其他会话已退出登录",
    signedOut = "已退出登录",
    signedOutLocally = "已在本设备退出；服务器会话将自动过期",
    memoSyncCompleted = "记录同步完成",
        memoSyncNoChanges = "记录已是最新状态",
    memoSyncNeedsReview = "部分记录更改需要处理冲突",
    memoSyncRejected = "服务器拒绝了部分更改；待推送内容已保留",
        memoSyncFailed = "记录同步失败；本地数据已保留",
    memoSyncServerMismatch = "待推送更改仍绑定到之前的服务器，未向当前服务器发送",
    memoSyncSessionExpired = "登录会话已过期，请重新登录后再同步。",
    memoSyncConflictResolved = "同步冲突已处理",
    askGenerationStopped = "已停止生成回答",
    askAnswerSaved = "回答已保存为记录",
    dataTransferFailed = "无法读取或写入备份，现有数据未被更改。",
    storageUnavailable = "无法读取本地数据，现有数据未被更改。",
    recordFilter = SillageRecordFilterStrings(
        unarchived = "记录",
        archived = "归档",
        favorited = "收藏",
        deleted = "删除",
    ),
    recordSearch = SillageRecordSearchStrings(
        label = "搜索记录",
        clearContentDescription = "清除搜索",
        searchContentDescription = "搜索",
    ),
    recordRow = SillageRecordRowStrings(
        blankRecord = "空白记录",
        entryDateLabel = "记录日期",
        moreActionsLabel = "更多记录操作",
        savingDescription = "正在保存记录",
        favoritedStatus = "收藏",
        archivedStatus = "归档",
    ),
    recordDetail = SillageRecordDetailStrings(
        entryDateLabel = "记录日期",
        blankRecord = "空白记录",
        favoritedStatus = "收藏",
        archivedStatus = "归档",
    ),
    recordActions = SillageRecordDetailActionStrings(
        editContentDescription = "编辑记录",
        moreContentDescription = "更多记录操作",
        favoriteAction = "添加到收藏",
        unfavoriteAction = "取消收藏",
        archiveAction = "归档",
        unarchiveAction = "取消归档",
        deleteAction = "移至最近删除",
        deleteTitle = "删除记录？",
        deleteSupporting = "可从最近删除中恢复这条记录。",
        confirmDeleteAction = "删除",
        cancelAction = "取消",
    ),
    ask = SillageNativeAskStrings(
        navigationLabel = "提问",
        title = "提问",
        savingAnswerDescription = "正在将回答保存为记录",
        conversationsDescription = "对话列表",
        contextDescription = "回答上下文",
        newConversationDescription = "新建对话",
        recentSevenDays = "最近 7 天",
        recentThirtyDays = "最近 30 天",
        allTime = "全部时间",
        recordsSource = "记录",
        summariesSource = "摘要",
        conversationsTitle = "对话",
        refresh = "刷新",
        noConversations = "还没有对话",
        untitledConversation = "未命名对话",
        currentConversation = { title -> "当前对话：$title" },
        contextTitle = "回答上下文",
        timeRange = "时间范围",
        recentSevenDaysShort = "7 天",
        recentThirtyDaysShort = "30 天",
        allTimeShort = "全部",
        sourceTitle = "来源",
        questionLabel = "问题",
        sendDescription = "发送问题",
        stopDescription = "停止生成",
        contextSummary = { scope, source -> "$scope · $source" },
        characterCount = { count -> "$count 个字符" },
        loadFailed = "无法加载对话。",
        retry = "重试",
        promptTitle = "向记录提问",
        promptExample = "上个月的工作发生了哪些变化？",
        regenerating = "正在重新生成回答……",
        thinking = "正在思考……",
        messageDescription = { isAssistant, content ->
            "${if (isAssistant) "Sillage" else "你"}：$content"
        },
        sourceCount = { count -> "$count 条来源" },
        sourceLabel = { source -> "${source.entryDate} · ${source.excerpt}" },
        showSourcesDescription = "显示来源",
        hideSourcesDescription = "隐藏来源",
        previousVariantDescription = "上一个回答版本",
        nextVariantDescription = "下一个回答版本",
        variantCounter = { position, total -> "$position / $total" },
        variantPositionDescription = { position, total ->
            "第 $position 个回答版本，共 $total 个"
        },
        regenerateDescription = "重新生成回答",
        generatingDescription = "正在生成回答",
        saveAsRecordDescription = "将回答保存为记录",
        savingDescription = "正在保存回答",
        answerCompleteDescription = "回答已完成",
        authenticationRequired = "请先登录已检查的 Sillage 服务器，再使用提问。",
        questionRequired = "请输入问题后再发送。",
        sendFailed = "无法生成回答，问题已保留。",
        variantFailed = "无法切换回答版本。",
        sourceUnavailable = "本设备上没有这条来源记录。",
        saveFailed = "无法将回答保存为记录。",
    ),
)
