package app.sillage.ui.application

import app.sillage.core.application.preferences.ClientPreferenceValues
import app.sillage.features.records.MemoListFilter
import app.sillage.ui.records.SillageRecordDetailActionStrings
import app.sillage.ui.records.SillageRecordDetailStrings
import app.sillage.ui.records.SillageRecordFilterStrings
import app.sillage.ui.records.SillageRecordRowStrings
import app.sillage.ui.records.SillageRecordSearchStrings

internal data class SillageNativeStrings(
    val appName: String,
    val records: String,
    val ask: String,
    val settings: String,
    val localMode: String,
    val newRecord: String,
    val saveRecord: String,
    val savingRecord: String,
    val back: String,
    val close: String,
    val recordDetails: String,
    val editRecord: String,
    val editorTitleNew: String,
    val editorTitleEdit: String,
    val entryDate: String,
    val entryDatePlaceholder: String,
    val content: String,
    val contentPlaceholder: String,
    val emptyRecordContent: String,
    val recordContentTooLarge: String,
    val invalidEntryDate: String,
    val noSelection: String,
    val noSearchResults: String,
    val emptyByFilter: Map<MemoListFilter, String>,
    val restore: String,
    val purge: String,
    val purgeTitle: String,
    val purgeSupporting: String,
    val confirm: String,
    val cancel: String,
    val discardTitle: String,
    val discardSupporting: String,
    val discard: String,
    val appearance: String,
    val darkTheme: String,
    val darkThemeSupporting: String,
    val language: String,
    val simplifiedChinese: String,
    val english: String,
    val data: String,
    val dataLocation: String,
    val openDataLocation: String,
    val openDataLocationSupporting: String,
    val exportBackup: String,
    val exportBackupSupporting: String,
    val restoreBackup: String,
    val restoreBackupSupporting: String,
    val restoreBackupTitle: String,
    val restoreBackupWarning: String,
    val platform: String,
    val version: String,
    val service: String,
    val serverAddress: String,
    val serverAddressPlaceholder: String,
    val checkServer: String,
    val checkingServer: String,
    val serverConnection: String,
    val serverConnectionAvailable: String,
    val serverConnectionFailed: String,
    val serverInitialization: String,
    val serverInitialized: String,
    val serverNeedsInitialization: String,
    val serverVersion: String,
    val apiVersion: String,
    val unknownValue: String,
    val mode: String,
    val offlineModeValue: String,
    val saved: String,
    val deleted: String,
    val restored: String,
    val purged: String,
    val backupExported: String,
    val backupRestored: String,
    val dataTransferFailed: String,
    val storageUnavailable: String,
    val recordFilter: SillageRecordFilterStrings,
    val recordSearch: SillageRecordSearchStrings,
    val recordRow: SillageRecordRowStrings,
    val recordDetail: SillageRecordDetailStrings,
    val recordActions: SillageRecordDetailActionStrings,
)

internal fun sillageNativeStrings(language: String): SillageNativeStrings {
    return if (language == ClientPreferenceValues.LANGUAGE_EN) englishStrings else chineseStrings
}

private val englishStrings = SillageNativeStrings(
    appName = "Sillage",
    records = "Records",
    ask = "Ask",
    settings = "Settings",
    localMode = "Local",
    newRecord = "New record",
    saveRecord = "Save record",
    savingRecord = "Saving record",
    back = "Back",
    close = "Close",
    recordDetails = "Record",
    editRecord = "Edit record",
    editorTitleNew = "New record",
    editorTitleEdit = "Edit record",
    entryDate = "Entry date",
    entryDatePlaceholder = "YYYY-MM-DD",
    content = "Content",
    contentPlaceholder = "Write a record...",
    emptyRecordContent = "Write something before saving.",
    recordContentTooLarge = "Keep record content within 1 MiB.",
    invalidEntryDate = "Enter a valid date in YYYY-MM-DD format.",
    noSelection = "Select a record",
    noSearchResults = "No matching records",
    emptyByFilter = mapOf(
        MemoListFilter.Unarchived to "No records yet",
        MemoListFilter.Archived to "No archived records",
        MemoListFilter.Favorited to "No favorite records",
        MemoListFilter.Deleted to "Recently Deleted is empty",
    ),
    restore = "Restore",
    purge = "Delete permanently",
    purgeTitle = "Delete permanently?",
    purgeSupporting = "This record cannot be restored after permanent deletion.",
    confirm = "Delete",
    cancel = "Cancel",
    discardTitle = "Discard changes?",
    discardSupporting = "Your unsaved changes will be lost.",
    discard = "Discard",
    appearance = "Appearance",
    darkTheme = "Dark theme",
    darkThemeSupporting = "Use the dark Sillage color scheme",
    language = "Language",
    simplifiedChinese = "Simplified Chinese",
    english = "English",
    data = "Data",
    dataLocation = "Local data",
    openDataLocation = "Open data folder",
    openDataLocationSupporting = "Show the device-local snapshot",
    exportBackup = "Export backup",
    exportBackupSupporting = "Save records and appearance as JSON",
    restoreBackup = "Restore backup",
    restoreBackupSupporting = "Replace local data from a Sillage JSON backup",
    restoreBackupTitle = "Restore this backup?",
    restoreBackupWarning = "Current records and appearance will be replaced. This cannot be undone.",
    platform = "Platform",
    version = "Version",
    service = "Service",
    serverAddress = "Sillage server",
    serverAddressPlaceholder = "https://sillage.example",
    checkServer = "Check server",
    checkingServer = "Checking server",
    serverConnection = "Connection",
    serverConnectionAvailable = "Available",
    serverConnectionFailed = "Could not reach a compatible Sillage server. Check the address and try again.",
    serverInitialization = "Instance",
    serverInitialized = "Initialized",
    serverNeedsInitialization = "Not initialized",
    serverVersion = "Server version",
    apiVersion = "API version",
    unknownValue = "Unknown",
    mode = "Mode",
    offlineModeValue = "Device only",
    saved = "Record saved",
    deleted = "Record moved to Recently Deleted",
    restored = "Record restored",
    purged = "Record permanently deleted",
    backupExported = "Backup exported",
    backupRestored = "Backup restored",
    dataTransferFailed = "The backup could not be read or written. Existing data was not changed.",
    storageUnavailable = "Local data could not be read. Existing data was not changed.",
    recordFilter = SillageRecordFilterStrings(
        unarchived = "Records",
        archived = "Archived",
        favorited = "Favorites",
        deleted = "Deleted",
    ),
    recordSearch = SillageRecordSearchStrings(
        label = "Search records",
        clearContentDescription = "Clear search",
        searchContentDescription = "Search",
    ),
    recordRow = SillageRecordRowStrings(
        blankRecord = "Blank record",
        entryDateLabel = "Entry date",
        moreActionsLabel = "More record actions",
        savingDescription = "Saving record",
        favoritedStatus = "Favorite",
        archivedStatus = "Archived",
    ),
    recordDetail = SillageRecordDetailStrings(
        entryDateLabel = "Entry date",
        blankRecord = "Blank record",
        favoritedStatus = "Favorite",
        archivedStatus = "Archived",
    ),
    recordActions = SillageRecordDetailActionStrings(
        editContentDescription = "Edit record",
        moreContentDescription = "More record actions",
        favoriteAction = "Add to favorites",
        unfavoriteAction = "Remove from favorites",
        archiveAction = "Archive",
        unarchiveAction = "Unarchive",
        deleteAction = "Move to Recently Deleted",
        deleteTitle = "Delete record?",
        deleteSupporting = "You can restore this record from Recently Deleted.",
        confirmDeleteAction = "Delete",
        cancelAction = "Cancel",
    ),
)

private val chineseStrings = SillageNativeStrings(
    appName = "Sillage",
    records = "记录",
    ask = "问答",
    settings = "设置",
    localMode = "本地",
    newRecord = "新建记录",
    saveRecord = "保存记录",
    savingRecord = "正在保存记录",
    back = "返回",
    close = "关闭",
    recordDetails = "记录",
    editRecord = "编辑记录",
    editorTitleNew = "新建记录",
    editorTitleEdit = "编辑记录",
    entryDate = "记录日期",
    entryDatePlaceholder = "YYYY-MM-DD",
    content = "内容",
    contentPlaceholder = "写下这条记录……",
    emptyRecordContent = "请输入记录内容。",
    recordContentTooLarge = "记录内容不能超过 1 MiB。",
    invalidEntryDate = "请输入 YYYY-MM-DD 格式的有效日期。",
    noSelection = "选择一条记录",
    noSearchResults = "没有匹配的记录",
    emptyByFilter = mapOf(
        MemoListFilter.Unarchived to "还没有记录",
        MemoListFilter.Archived to "没有已归档记录",
        MemoListFilter.Favorited to "没有收藏记录",
        MemoListFilter.Deleted to "最近删除为空",
    ),
    restore = "恢复",
    purge = "永久删除",
    purgeTitle = "永久删除？",
    purgeSupporting = "永久删除后无法恢复这条记录。",
    confirm = "删除",
    cancel = "取消",
    discardTitle = "放弃更改？",
    discardSupporting = "尚未保存的更改将会丢失。",
    discard = "放弃",
    appearance = "外观",
    darkTheme = "深色主题",
    darkThemeSupporting = "使用 Sillage 深色配色",
    language = "语言",
    simplifiedChinese = "简体中文",
    english = "English",
    data = "数据",
    dataLocation = "本地数据",
    openDataLocation = "打开数据文件夹",
    openDataLocationSupporting = "查看保存在设备上的快照",
    exportBackup = "导出备份",
    exportBackupSupporting = "将记录和外观设置保存为 JSON",
    restoreBackup = "恢复备份",
    restoreBackupSupporting = "用 Sillage JSON 备份替换本地数据",
    restoreBackupTitle = "恢复这个备份？",
    restoreBackupWarning = "当前记录和外观设置将被替换，且无法撤销。",
    platform = "平台",
    version = "版本",
    service = "服务",
    serverAddress = "Sillage 服务器",
    serverAddressPlaceholder = "https://sillage.example",
    checkServer = "检查服务器",
    checkingServer = "正在检查服务器",
    serverConnection = "连接状态",
    serverConnectionAvailable = "可用",
    serverConnectionFailed = "无法连接兼容的 Sillage 服务器，请检查地址后重试。",
    serverInitialization = "实例状态",
    serverInitialized = "已初始化",
    serverNeedsInitialization = "未初始化",
    serverVersion = "服务器版本",
    apiVersion = "API 版本",
    unknownValue = "未知",
    mode = "模式",
    offlineModeValue = "仅本设备",
    saved = "记录已保存",
    deleted = "记录已移至最近删除",
    restored = "记录已恢复",
    purged = "记录已永久删除",
    backupExported = "备份已导出",
    backupRestored = "备份已恢复",
    dataTransferFailed = "无法读取或写入备份，现有数据未被更改。",
    storageUnavailable = "无法读取本地数据，现有数据未被更改。",
    recordFilter = SillageRecordFilterStrings(
        unarchived = "记录",
        archived = "归档",
        favorited = "收藏",
        deleted = "删除",
    ),
    recordSearch = SillageRecordSearchStrings(
        label = "搜索记录",
        clearContentDescription = "清除搜索",
        searchContentDescription = "搜索",
    ),
    recordRow = SillageRecordRowStrings(
        blankRecord = "空白记录",
        entryDateLabel = "记录日期",
        moreActionsLabel = "更多记录操作",
        savingDescription = "正在保存记录",
        favoritedStatus = "收藏",
        archivedStatus = "归档",
    ),
    recordDetail = SillageRecordDetailStrings(
        entryDateLabel = "记录日期",
        blankRecord = "空白记录",
        favoritedStatus = "收藏",
        archivedStatus = "归档",
    ),
    recordActions = SillageRecordDetailActionStrings(
        editContentDescription = "编辑记录",
        moreContentDescription = "更多记录操作",
        favoriteAction = "添加到收藏",
        unfavoriteAction = "取消收藏",
        archiveAction = "归档",
        unarchiveAction = "取消归档",
        deleteAction = "移至最近删除",
        deleteTitle = "删除记录？",
        deleteSupporting = "可从最近删除中恢复这条记录。",
        confirmDeleteAction = "删除",
        cancelAction = "取消",
    ),
)
