// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/attachment_service.proto (package sillage.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Attachment } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/attachment_service.proto.
 */
export const file_api_v1_attachment_service: GenFile = /*@__PURE__*/
  fileDesc("Ch9hcGkvdjEvYXR0YWNobWVudF9zZXJ2aWNlLnByb3RvEg5zaWxsYWdlLmFwaS52MSIjChRHZXRBdHRhY2htZW50UmVxdWVzdBILCgN1aWQYASABKAkiRAoSQXR0YWNobWVudFJlc3BvbnNlEi4KCmF0dGFjaG1lbnQYASABKAsyGi5zaWxsYWdlLmFwaS52MS5BdHRhY2htZW50MpEBChFBdHRhY2htZW50U2VydmljZRJ8Cg1HZXRBdHRhY2htZW50EiQuc2lsbGFnZS5hcGkudjEuR2V0QXR0YWNobWVudFJlcXVlc3QaIi5zaWxsYWdlLmFwaS52MS5BdHRhY2htZW50UmVzcG9uc2UiIYLT5JMCGxIZL2FwaS92MS9hdHRhY2htZW50cy97dWlkfUK6AQoSY29tLnNpbGxhZ2UuYXBpLnYxQhZBdHRhY2htZW50U2VydmljZVByb3RvUAFaMmdpdGh1Yi5jb20vbWlvZmVsaXgvc2lsbGFnZS9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDU0FYqgIOU2lsbGFnZS5BcGkuVjHKAg5TaWxsYWdlXEFwaVxWMeICGlNpbGxhZ2VcQXBpXFYxXEdQQk1ldGFkYXRh6gIQU2lsbGFnZTo6QXBpOjpWMWIGcHJvdG8z", [file_api_v1_common, file_google_api_annotations]);

/**
 * @generated from message sillage.api.v1.GetAttachmentRequest
 */
export type GetAttachmentRequest = Message<"sillage.api.v1.GetAttachmentRequest"> & {
  /**
   * @generated from field: string uid = 1;
   */
  uid: string;
};

/**
 * Describes the message sillage.api.v1.GetAttachmentRequest.
 * Use `create(GetAttachmentRequestSchema)` to create a new message.
 */
export const GetAttachmentRequestSchema: GenMessage<GetAttachmentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 0);

/**
 * @generated from message sillage.api.v1.AttachmentResponse
 */
export type AttachmentResponse = Message<"sillage.api.v1.AttachmentResponse"> & {
  /**
   * @generated from field: sillage.api.v1.Attachment attachment = 1;
   */
  attachment?: Attachment | undefined;
};

/**
 * Describes the message sillage.api.v1.AttachmentResponse.
 * Use `create(AttachmentResponseSchema)` to create a new message.
 */
export const AttachmentResponseSchema: GenMessage<AttachmentResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 1);

/**
 * @generated from service sillage.api.v1.AttachmentService
 */
export const AttachmentService: GenService<{
  /**
   * @generated from rpc sillage.api.v1.AttachmentService.GetAttachment
   */
  getAttachment: {
    methodKind: "unary";
    input: typeof GetAttachmentRequestSchema;
    output: typeof AttachmentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_attachment_service, 0);

