// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/auth_service.proto (package sillage.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Account } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/auth_service.proto.
 */
export const file_api_v1_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvYXV0aF9zZXJ2aWNlLnByb3RvEg5zaWxsYWdlLmFwaS52MSISChBCb290c3RyYXBSZXF1ZXN0IigKEUJvb3RzdHJhcFJlc3BvbnNlEhMKC2luaXRpYWxpemVkGAEgASgIIk0KEUluaXRpYWxpemVSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSIzCg1TaWduSW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIhAKDlJlZnJlc2hSZXF1ZXN0IhAKDlNpZ25PdXRSZXF1ZXN0IgsKCU1lUmVxdWVzdCI2CgpNZVJlc3BvbnNlEigKB2FjY291bnQYASABKAsyFy5zaWxsYWdlLmFwaS52MS5BY2NvdW50ImIKDEF1dGhSZXNwb25zZRIoCgdhY2NvdW50GAEgASgLMhcuc2lsbGFnZS5hcGkudjEuQWNjb3VudBIUCgxhY2Nlc3NfdG9rZW4YAiABKAkSEgoKZXhwaXJlc19hdBgDIAEoCTL9BAoLQXV0aFNlcnZpY2UScAoJQm9vdHN0cmFwEiAuc2lsbGFnZS5hcGkudjEuQm9vdHN0cmFwUmVxdWVzdBohLnNpbGxhZ2UuYXBpLnYxLkJvb3RzdHJhcFJlc3BvbnNlIh6C0+STAhgSFi9hcGkvdjEvYXV0aC9ib290c3RyYXAScQoKSW5pdGlhbGl6ZRIhLnNpbGxhZ2UuYXBpLnYxLkluaXRpYWxpemVSZXF1ZXN0Ghwuc2lsbGFnZS5hcGkudjEuQXV0aFJlc3BvbnNlIiKC0+STAhw6ASoiFy9hcGkvdjEvYXV0aC9pbml0aWFsaXplEmUKBlNpZ25JbhIdLnNpbGxhZ2UuYXBpLnYxLlNpZ25JblJlcXVlc3QaHC5zaWxsYWdlLmFwaS52MS5BdXRoUmVzcG9uc2UiHoLT5JMCGDoBKiITL2FwaS92MS9hdXRoL3NpZ25pbhJoCgdSZWZyZXNoEh4uc2lsbGFnZS5hcGkudjEuUmVmcmVzaFJlcXVlc3QaHC5zaWxsYWdlLmFwaS52MS5BdXRoUmVzcG9uc2UiH4LT5JMCGToBKiIUL2FwaS92MS9hdXRoL3JlZnJlc2gSYgoHU2lnbk91dBIeLnNpbGxhZ2UuYXBpLnYxLlNpZ25PdXRSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Ih+C0+STAhk6ASoiFC9hcGkvdjEvYXV0aC9zaWdub3V0ElQKAk1lEhkuc2lsbGFnZS5hcGkudjEuTWVSZXF1ZXN0Ghouc2lsbGFnZS5hcGkudjEuTWVSZXNwb25zZSIXgtPkkwIREg8vYXBpL3YxL2F1dGgvbWVCtAEKEmNvbS5zaWxsYWdlLmFwaS52MUIQQXV0aFNlcnZpY2VQcm90b1ABWjJnaXRodWIuY29tL21pb2ZlbGl4L3NpbGxhZ2UvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA1NBWKoCDlNpbGxhZ2UuQXBpLlYxygIOU2lsbGFnZVxBcGlcVjHiAhpTaWxsYWdlXEFwaVxWMVxHUEJNZXRhZGF0YeoCEFNpbGxhZ2U6OkFwaTo6VjFiBnByb3RvMw", [file_api_v1_common, file_google_api_annotations, file_google_protobuf_empty]);

/**
 * @generated from message sillage.api.v1.BootstrapRequest
 */
export type BootstrapRequest = Message<"sillage.api.v1.BootstrapRequest"> & {
};

/**
 * Describes the message sillage.api.v1.BootstrapRequest.
 * Use `create(BootstrapRequestSchema)` to create a new message.
 */
export const BootstrapRequestSchema: GenMessage<BootstrapRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 0);

/**
 * @generated from message sillage.api.v1.BootstrapResponse
 */
export type BootstrapResponse = Message<"sillage.api.v1.BootstrapResponse"> & {
  /**
   * @generated from field: bool initialized = 1;
   */
  initialized: boolean;
};

/**
 * Describes the message sillage.api.v1.BootstrapResponse.
 * Use `create(BootstrapResponseSchema)` to create a new message.
 */
export const BootstrapResponseSchema: GenMessage<BootstrapResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 1);

/**
 * @generated from message sillage.api.v1.InitializeRequest
 */
export type InitializeRequest = Message<"sillage.api.v1.InitializeRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message sillage.api.v1.InitializeRequest.
 * Use `create(InitializeRequestSchema)` to create a new message.
 */
export const InitializeRequestSchema: GenMessage<InitializeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 2);

/**
 * @generated from message sillage.api.v1.SignInRequest
 */
export type SignInRequest = Message<"sillage.api.v1.SignInRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message sillage.api.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 3);

/**
 * @generated from message sillage.api.v1.RefreshRequest
 */
export type RefreshRequest = Message<"sillage.api.v1.RefreshRequest"> & {
};

/**
 * Describes the message sillage.api.v1.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 4);

/**
 * @generated from message sillage.api.v1.SignOutRequest
 */
export type SignOutRequest = Message<"sillage.api.v1.SignOutRequest"> & {
};

/**
 * Describes the message sillage.api.v1.SignOutRequest.
 * Use `create(SignOutRequestSchema)` to create a new message.
 */
export const SignOutRequestSchema: GenMessage<SignOutRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 5);

/**
 * @generated from message sillage.api.v1.MeRequest
 */
export type MeRequest = Message<"sillage.api.v1.MeRequest"> & {
};

/**
 * Describes the message sillage.api.v1.MeRequest.
 * Use `create(MeRequestSchema)` to create a new message.
 */
export const MeRequestSchema: GenMessage<MeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 6);

/**
 * @generated from message sillage.api.v1.MeResponse
 */
export type MeResponse = Message<"sillage.api.v1.MeResponse"> & {
  /**
   * @generated from field: sillage.api.v1.Account account = 1;
   */
  account?: Account | undefined;
};

/**
 * Describes the message sillage.api.v1.MeResponse.
 * Use `create(MeResponseSchema)` to create a new message.
 */
export const MeResponseSchema: GenMessage<MeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 7);

/**
 * @generated from message sillage.api.v1.AuthResponse
 */
export type AuthResponse = Message<"sillage.api.v1.AuthResponse"> & {
  /**
   * @generated from field: sillage.api.v1.Account account = 1;
   */
  account?: Account | undefined;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string expires_at = 3;
   */
  expiresAt: string;
};

/**
 * Describes the message sillage.api.v1.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 8);

/**
 * @generated from service sillage.api.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc sillage.api.v1.AuthService.Bootstrap
   */
  bootstrap: {
    methodKind: "unary";
    input: typeof BootstrapRequestSchema;
    output: typeof BootstrapResponseSchema;
  },
  /**
   * @generated from rpc sillage.api.v1.AuthService.Initialize
   */
  initialize: {
    methodKind: "unary";
    input: typeof InitializeRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc sillage.api.v1.AuthService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc sillage.api.v1.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc sillage.api.v1.AuthService.SignOut
   */
  signOut: {
    methodKind: "unary";
    input: typeof SignOutRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc sillage.api.v1.AuthService.Me
   */
  me: {
    methodKind: "unary";
    input: typeof MeRequestSchema;
    output: typeof MeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_auth_service, 0);

