// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/settings_service.proto (package sillage.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AIProfile } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/settings_service.proto.
 */
export const file_api_v1_settings_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1hcGkvdjEvc2V0dGluZ3Nfc2VydmljZS5wcm90bxIOc2lsbGFnZS5hcGkudjEiFgoUR2V0QUlTZXR0aW5nc1JlcXVlc3QiSgoWUGF0Y2hBSVNldHRpbmdzUmVxdWVzdBIwCghwcm9maWxlcxgBIAMoCzIeLnNpbGxhZ2UuYXBpLnYxLkFJUHJvZmlsZUlucHV0IskBCg5BSVByb2ZpbGVJbnB1dBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhAKCHByb3ZpZGVyGAMgASgJEhAKCGJhc2VfdXJsGAQgASgJEg0KBW1vZGVsGAUgASgJEhMKC3RlbXBlcmF0dXJlGAYgASgBEhIKCm1heF90b2tlbnMYByABKAMSDwoHZW5hYmxlZBgIIAEoCBIOCgZhY3RpdmUYCSABKAgSFAoHYXBpX2tleRgKIAEoCUgAiAEBQgoKCF9hcGlfa2V5IkEKEkFJU2V0dGluZ3NSZXNwb25zZRIrCghwcm9maWxlcxgBIAMoCzIZLnNpbGxhZ2UuYXBpLnYxLkFJUHJvZmlsZTKIAgoPU2V0dGluZ3NTZXJ2aWNlEnYKDUdldEFJU2V0dGluZ3MSJC5zaWxsYWdlLmFwaS52MS5HZXRBSVNldHRpbmdzUmVxdWVzdBoiLnNpbGxhZ2UuYXBpLnYxLkFJU2V0dGluZ3NSZXNwb25zZSIbgtPkkwIVEhMvYXBpL3YxL3NldHRpbmdzL2FpEn0KD1BhdGNoQUlTZXR0aW5ncxImLnNpbGxhZ2UuYXBpLnYxLlBhdGNoQUlTZXR0aW5nc1JlcXVlc3QaIi5zaWxsYWdlLmFwaS52MS5BSVNldHRpbmdzUmVzcG9uc2UiHoLT5JMCGDoBKjITL2FwaS92MS9zZXR0aW5ncy9haUK4AQoSY29tLnNpbGxhZ2UuYXBpLnYxQhRTZXR0aW5nc1NlcnZpY2VQcm90b1ABWjJnaXRodWIuY29tL21pb2ZlbGl4L3NpbGxhZ2UvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA1NBWKoCDlNpbGxhZ2UuQXBpLlYxygIOU2lsbGFnZVxBcGlcVjHiAhpTaWxsYWdlXEFwaVxWMVxHUEJNZXRhZGF0YeoCEFNpbGxhZ2U6OkFwaTo6VjFiBnByb3RvMw", [file_api_v1_common, file_google_api_annotations]);

/**
 * @generated from message sillage.api.v1.GetAISettingsRequest
 */
export type GetAISettingsRequest = Message<"sillage.api.v1.GetAISettingsRequest"> & {
};

/**
 * Describes the message sillage.api.v1.GetAISettingsRequest.
 * Use `create(GetAISettingsRequestSchema)` to create a new message.
 */
export const GetAISettingsRequestSchema: GenMessage<GetAISettingsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_settings_service, 0);

/**
 * @generated from message sillage.api.v1.PatchAISettingsRequest
 */
export type PatchAISettingsRequest = Message<"sillage.api.v1.PatchAISettingsRequest"> & {
  /**
   * @generated from field: repeated sillage.api.v1.AIProfileInput profiles = 1;
   */
  profiles: AIProfileInput[];
};

/**
 * Describes the message sillage.api.v1.PatchAISettingsRequest.
 * Use `create(PatchAISettingsRequestSchema)` to create a new message.
 */
export const PatchAISettingsRequestSchema: GenMessage<PatchAISettingsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_settings_service, 1);

/**
 * @generated from message sillage.api.v1.AIProfileInput
 */
export type AIProfileInput = Message<"sillage.api.v1.AIProfileInput"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string provider = 3;
   */
  provider: string;

  /**
   * @generated from field: string base_url = 4;
   */
  baseUrl: string;

  /**
   * @generated from field: string model = 5;
   */
  model: string;

  /**
   * @generated from field: double temperature = 6;
   */
  temperature: number;

  /**
   * @generated from field: int64 max_tokens = 7;
   */
  maxTokens: bigint;

  /**
   * @generated from field: bool enabled = 8;
   */
  enabled: boolean;

  /**
   * @generated from field: bool active = 9;
   */
  active: boolean;

  /**
   * @generated from field: optional string api_key = 10;
   */
  apiKey?: string | undefined;
};

/**
 * Describes the message sillage.api.v1.AIProfileInput.
 * Use `create(AIProfileInputSchema)` to create a new message.
 */
export const AIProfileInputSchema: GenMessage<AIProfileInput> = /*@__PURE__*/
  messageDesc(file_api_v1_settings_service, 2);

/**
 * @generated from message sillage.api.v1.AISettingsResponse
 */
export type AISettingsResponse = Message<"sillage.api.v1.AISettingsResponse"> & {
  /**
   * @generated from field: repeated sillage.api.v1.AIProfile profiles = 1;
   */
  profiles: AIProfile[];
};

/**
 * Describes the message sillage.api.v1.AISettingsResponse.
 * Use `create(AISettingsResponseSchema)` to create a new message.
 */
export const AISettingsResponseSchema: GenMessage<AISettingsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_settings_service, 3);

/**
 * @generated from service sillage.api.v1.SettingsService
 */
export const SettingsService: GenService<{
  /**
   * @generated from rpc sillage.api.v1.SettingsService.GetAISettings
   */
  getAISettings: {
    methodKind: "unary";
    input: typeof GetAISettingsRequestSchema;
    output: typeof AISettingsResponseSchema;
  },
  /**
   * @generated from rpc sillage.api.v1.SettingsService.PatchAISettings
   */
  patchAISettings: {
    methodKind: "unary";
    input: typeof PatchAISettingsRequestSchema;
    output: typeof AISettingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_settings_service, 0);

